version: '3.8'

services:
  pytest:
    image: fastcmd-base
    volumes:
      - .:/app
    working_dir: /app
    command: pytest
    environment:
      - PYTHONPATH=/app
  
  lint:
    image: fastcmd-base
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        black src tests &&
        isort src tests &&
        flake8 src tests &&
        mypy src tests"
    environment:
      - PYTHONPATH=/app
