[tool.black]
line-length = 79
target-version = ['py310']
exclude = '''
/(
    \.venv|
    venv|
    venv-dev|
    build|
    dist|
    \.git|
    __pycache__|
    migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 79

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
disallow_untyped_defs = true
