name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base image
        run: docker build -t fastcmd-base -f docker/Dockerfile.dev .

      - name: Run linting
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app fastcmd-base bash -c "
            black src tests &&
            isort src tests &&
            flake8 src tests &&
            mypy src tests"

      - name: Run tests
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app fastcmd-base pytest

  cd:
    name: CD
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get version
        id: get_version
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          # Increment patch version
          new_version=$(echo $latest_tag | awk -F. -v OFS=. '{$NF = $NF + 1;} 1')
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag ${{ steps.get_version.outputs.new_version }}
          git push origin ${{ steps.get_version.outputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.app
          push: true
          tags: |
            lukakap/fastcmd:latest
            lukakap/fastcmd:${{ steps.get_version.outputs.new_version }}
          build-args: |
            VERSION=${{ steps.get_version.outputs.new_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 